//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Register_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Register_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Account.Register.en", typeof(Register_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diaspora.
        /// </summary>
        internal static string diaspore {
            get {
                return ResourceManager.GetString("diaspore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Day.
        /// </summary>
        internal static string ditaLindjes {
            get {
                return ResourceManager.GetString("ditaLindjes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string emaili {
            get {
                return ResourceManager.GetString("emaili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string emri {
            get {
                return ResourceManager.GetString("emri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string femer {
            get {
                return ResourceManager.GetString("femer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string fjalekalimi {
            get {
                return ResourceManager.GetString("fjalekalimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string gjinia {
            get {
                return ResourceManager.GetString("gjinia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Login.
        /// </summary>
        internal static string keniLlogari {
            get {
                return ResourceManager.GetString("keniLlogari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string konfirmoFjalekalimin {
            get {
                return ResourceManager.GetString("konfirmoFjalekalimin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosovo.
        /// </summary>
        internal static string kosove {
            get {
                return ResourceManager.GetString("kosove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonia.
        /// </summary>
        internal static string maqedoni {
            get {
                return ResourceManager.GetString("maqedoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string mashkull {
            get {
                return ResourceManager.GetString("mashkull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string mbiemri {
            get {
                return ResourceManager.GetString("mbiemri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Month.
        /// </summary>
        internal static string muajiLindjes {
            get {
                return ResourceManager.GetString("muajiLindjes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept terms and conditions.
        /// </summary>
        internal static string pranojKushtet {
            get {
                return ResourceManager.GetString("pranojKushtet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string regjistrohu {
            get {
                return ResourceManager.GetString("regjistrohu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania.
        /// </summary>
        internal static string shqiperi {
            get {
                return ResourceManager.GetString("shqiperi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Year.
        /// </summary>
        internal static string vitiLindjes {
            get {
                return ResourceManager.GetString("vitiLindjes", resourceCulture);
            }
        }
    }
}
