//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Checkout {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Checkout.Index.en", typeof(Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        internal static string adresa {
            get {
                return ResourceManager.GetString("adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Coupon.
        /// </summary>
        internal static string aplikoKuponin {
            get {
                return ResourceManager.GetString("aplikoKuponin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Details.
        /// </summary>
        internal static string detajetFaturimit {
            get {
                return ResourceManager.GetString("detajetFaturimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string emaili {
            get {
                return ResourceManager.GetString("emaili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string emri {
            get {
                return ResourceManager.GetString("emri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a coupon?.
        /// </summary>
        internal static string keniKupon {
            get {
                return ResourceManager.GetString("keniKupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string kodiPostal {
            get {
                return ResourceManager.GetString("kodiPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        internal static string konfirmoPorosine {
            get {
                return ResourceManager.GetString("konfirmoPorosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon code.
        /// </summary>
        internal static string kuponCode {
            get {
                return ResourceManager.GetString("kuponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string mbiemri {
            get {
                return ResourceManager.GetString("mbiemri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with cash.
        /// </summary>
        internal static string paymentMethod1 {
            get {
                return ResourceManager.GetString("paymentMethod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is made after the order is received..
        /// </summary>
        internal static string paymentMethod1Desc {
            get {
                return ResourceManager.GetString("paymentMethod1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string paymentMethod2 {
            get {
                return ResourceManager.GetString("paymentMethod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your payment by bank card..
        /// </summary>
        internal static string paymentMethod2Desc {
            get {
                return ResourceManager.GetString("paymentMethod2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order.
        /// </summary>
        internal static string porosiaJuaj {
            get {
                return ResourceManager.GetString("porosiaJuaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string produktet {
            get {
                return ResourceManager.GetString("produktet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string qyteti {
            get {
                return ResourceManager.GetString("qyteti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Notes.
        /// </summary>
        internal static string shenimePerPorosi {
            get {
                return ResourceManager.GetString("shenimePerPorosi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes about your order, e.g. special notes for delivery..
        /// </summary>
        internal static string shenimePerPorosiPlace {
            get {
                return ResourceManager.GetString("shenimePerPorosiPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string shteti {
            get {
                return ResourceManager.GetString("shteti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string subtotali {
            get {
                return ResourceManager.GetString("subtotali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string telefoni {
            get {
                return ResourceManager.GetString("telefoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string totali {
            get {
                return ResourceManager.GetString("totali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment.
        /// </summary>
        internal static string transporti {
            get {
                return ResourceManager.GetString("transporti", resourceCulture);
            }
        }
    }
}
