//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Checkout {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Checkout.Index.sq", typeof(Index_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa / Rruga.
        /// </summary>
        internal static string adresa {
            get {
                return ResourceManager.GetString("adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apliko kuponin.
        /// </summary>
        internal static string aplikoKuponin {
            get {
                return ResourceManager.GetString("aplikoKuponin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detajet e faturimit.
        /// </summary>
        internal static string detajetFaturimit {
            get {
                return ResourceManager.GetString("detajetFaturimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emaili.
        /// </summary>
        internal static string emaili {
            get {
                return ResourceManager.GetString("emaili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        internal static string emri {
            get {
                return ResourceManager.GetString("emri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keni kupon?.
        /// </summary>
        internal static string keniKupon {
            get {
                return ResourceManager.GetString("keniKupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi Postal.
        /// </summary>
        internal static string kodiPostal {
            get {
                return ResourceManager.GetString("kodiPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmo porosinë.
        /// </summary>
        internal static string konfirmoPorosine {
            get {
                return ResourceManager.GetString("konfirmoPorosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi i kuponit.
        /// </summary>
        internal static string kuponCode {
            get {
                return ResourceManager.GetString("kuponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbiemri.
        /// </summary>
        internal static string mbiemri {
            get {
                return ResourceManager.GetString("mbiemri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paguaj me para në dorë.
        /// </summary>
        internal static string paymentMethod1 {
            get {
                return ResourceManager.GetString("paymentMethod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagesa bëhet pasi të pranohet porosia..
        /// </summary>
        internal static string paymentMethod1Desc {
            get {
                return ResourceManager.GetString("paymentMethod1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paguaj me kartelë.
        /// </summary>
        internal static string paymentMethod2 {
            get {
                return ResourceManager.GetString("paymentMethod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kryeni pagesën tuaj me kartelë bankare..
        /// </summary>
        internal static string paymentMethod2Desc {
            get {
                return ResourceManager.GetString("paymentMethod2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porosia juaj.
        /// </summary>
        internal static string porosiaJuaj {
            get {
                return ResourceManager.GetString("porosiaJuaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktet.
        /// </summary>
        internal static string produktet {
            get {
                return ResourceManager.GetString("produktet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qyteti.
        /// </summary>
        internal static string qyteti {
            get {
                return ResourceManager.GetString("qyteti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shënime për porosinë tuaj.
        /// </summary>
        internal static string shenimePerPorosi {
            get {
                return ResourceManager.GetString("shenimePerPorosi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shënime për porosinë tuaj, p.sh. shënime të veçanta për dorëzim..
        /// </summary>
        internal static string shenimePerPorosiPlace {
            get {
                return ResourceManager.GetString("shenimePerPorosiPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shteti.
        /// </summary>
        internal static string shteti {
            get {
                return ResourceManager.GetString("shteti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotali.
        /// </summary>
        internal static string subtotali {
            get {
                return ResourceManager.GetString("subtotali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoni.
        /// </summary>
        internal static string telefoni {
            get {
                return ResourceManager.GetString("telefoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totali.
        /// </summary>
        internal static string totali {
            get {
                return ResourceManager.GetString("totali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporti.
        /// </summary>
        internal static string transporti {
            get {
                return ResourceManager.GetString("transporti", resourceCulture);
            }
        }
    }
}
