//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Products {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Products.Index.sq", typeof(Index_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asnjë produkt i gjetur..
        /// </summary>
        internal static string asnjeProdukt {
            get {
                return ResourceManager.GetString("asnjeProdukt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duke treguar.
        /// </summary>
        internal static string dukeTreguar {
            get {
                return ResourceManager.GetString("dukeTreguar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro me kategori.
        /// </summary>
        internal static string filtroMeKategori {
            get {
                return ResourceManager.GetString("filtroMeKategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërko.
        /// </summary>
        internal static string kerko {
            get {
                return ResourceManager.GetString("kerko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërko këtu....
        /// </summary>
        internal static string kerkoKetu {
            get {
                return ResourceManager.GetString("kerkoKetu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nga.
        /// </summary>
        internal static string nga {
            get {
                return ResourceManager.GetString("nga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to produkte.
        /// </summary>
        internal static string produkte {
            get {
                return ResourceManager.GetString("produkte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendit sipas çmimit: të Lartë deri tek të Ulët.
        /// </summary>
        internal static string renditSipasLarteUlet {
            get {
                return ResourceManager.GetString("renditSipasLarteUlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendit sipas revelencës.
        /// </summary>
        internal static string renditSipasRevelences {
            get {
                return ResourceManager.GetString("renditSipasRevelences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendit sipas çmimit: të Ulët deri tek të Lartë.
        /// </summary>
        internal static string renditSipasUletLarte {
            get {
                return ResourceManager.GetString("renditSipasUletLarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto ne shportë.
        /// </summary>
        internal static string shtoNeShporte {
            get {
                return ResourceManager.GetString("shtoNeShporte", resourceCulture);
            }
        }
    }
}
