//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Products {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductDetails_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductDetails_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Products.ProductDetails.en", typeof(ProductDetails_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Products Found!.
        /// </summary>
        internal static string asnjeProdukt {
            get {
                return ResourceManager.GetString("asnjeProdukt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        internal static string detajet {
            get {
                return ResourceManager.GetString("detajet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLD OUT.
        /// </summary>
        internal static string eshitur {
            get {
                return ResourceManager.GetString("eshitur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string krahaso {
            get {
                return ResourceManager.GetString("krahaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment methods:.
        /// </summary>
        internal static string mundesitePagesave {
            get {
                return ResourceManager.GetString("mundesitePagesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string pershkrimi {
            get {
                return ResourceManager.GetString("pershkrimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description.
        /// </summary>
        internal static string pershkrimiProduktit {
            get {
                return ResourceManager.GetString("pershkrimiProduktit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You save.
        /// </summary>
        internal static string saving {
            get {
                return ResourceManager.GetString("saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string shikime {
            get {
                return ResourceManager.GetString("shikime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Wishlist.
        /// </summary>
        internal static string shtoNeListeneDeshirave {
            get {
                return ResourceManager.GetString("shtoNeListeneDeshirave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        internal static string shtoNeShporte {
            get {
                return ResourceManager.GetString("shtoNeShporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar.
        /// </summary>
        internal static string tengjashme {
            get {
                return ResourceManager.GetString("tengjashme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string vleresimet {
            get {
                return ResourceManager.GetString("vleresimet", resourceCulture);
            }
        }
    }
}
