//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Cart {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Cart.Index.sq", typeof(Index_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikoni kuponin.
        /// </summary>
        internal static string aplikoKodin {
            get {
                return ResourceManager.GetString("aplikoKodin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikujt e shportës suaj.
        /// </summary>
        internal static string artikujtShportes {
            get {
                return ResourceManager.GetString("artikujtShportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmimi.
        /// </summary>
        internal static string cmimi {
            get {
                return ResourceManager.GetString("cmimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shkruani destinacionin tuaj për të marrë një vlerësim të transportit..
        /// </summary>
        internal static string destinacioni {
            get {
                return ResourceManager.GetString("destinacioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri i produktit.
        /// </summary>
        internal static string emriProduktit {
            get {
                return ResourceManager.GetString("emriProduktit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        internal static string foto {
            get {
                return ResourceManager.GetString("foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futni kodin tuaj të kuponit nëse keni një të tillë..
        /// </summary>
        internal static string futKodin {
            get {
                return ResourceManager.GetString("futKodin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulo.
        /// </summary>
        internal static string kalkulo {
            get {
                return ResourceManager.GetString("kalkulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi Postal.
        /// </summary>
        internal static string kodiPostal {
            get {
                return ResourceManager.GetString("kodiPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastroni shportën.
        /// </summary>
        internal static string pastroShporten {
            get {
                return ResourceManager.GetString("pastroShporten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përditso Shportën.
        /// </summary>
        internal static string perditsoShporten {
            get {
                return ResourceManager.GetString("perditsoShporten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdorni kodin e kuponit.
        /// </summary>
        internal static string perdorKodin {
            get {
                return ResourceManager.GetString("perdorKodin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sasia.
        /// </summary>
        internal static string sasia {
            get {
                return ResourceManager.GetString("sasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shporta juaj është e zbrazët..
        /// </summary>
        internal static string shportaZbrazet {
            get {
                return ResourceManager.GetString("shportaZbrazet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shteti.
        /// </summary>
        internal static string shteti {
            get {
                return ResourceManager.GetString("shteti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotali.
        /// </summary>
        internal static string subtotali {
            get {
                return ResourceManager.GetString("subtotali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totali i shportës.
        /// </summary>
        internal static string totali {
            get {
                return ResourceManager.GetString("totali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total produkte.
        /// </summary>
        internal static string totalProdukte {
            get {
                return ResourceManager.GetString("totalProdukte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totali i transportit.
        /// </summary>
        internal static string totalTransporti {
            get {
                return ResourceManager.GetString("totalTransporti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vazhdoni me pagesë.
        /// </summary>
        internal static string vazhdo {
            get {
                return ResourceManager.GetString("vazhdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vazhdoni me blerje.
        /// </summary>
        internal static string vazhdoniBlerje {
            get {
                return ResourceManager.GetString("vazhdoniBlerje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlerësimi i transportit dhe taksave.
        /// </summary>
        internal static string vleresimiTransportit {
            get {
                return ResourceManager.GetString("vleresimiTransportit", resourceCulture);
            }
        }
    }
}
