//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Cart {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Cart.Index.en", typeof(Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Coupon.
        /// </summary>
        internal static string aplikoKodin {
            get {
                return ResourceManager.GetString("aplikoKodin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items in your cart.
        /// </summary>
        internal static string artikujtShportes {
            get {
                return ResourceManager.GetString("artikujtShportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string cmimi {
            get {
                return ResourceManager.GetString("cmimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your destination to get a shipping estimate..
        /// </summary>
        internal static string destinacioni {
            get {
                return ResourceManager.GetString("destinacioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string emriProduktit {
            get {
                return ResourceManager.GetString("emriProduktit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string foto {
            get {
                return ResourceManager.GetString("foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your coupon code if you have one..
        /// </summary>
        internal static string futKodin {
            get {
                return ResourceManager.GetString("futKodin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get A Quote.
        /// </summary>
        internal static string kalkulo {
            get {
                return ResourceManager.GetString("kalkulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string kodiPostal {
            get {
                return ResourceManager.GetString("kodiPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Shopping Cart.
        /// </summary>
        internal static string pastroShporten {
            get {
                return ResourceManager.GetString("pastroShporten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Shopping Cart.
        /// </summary>
        internal static string perditsoShporten {
            get {
                return ResourceManager.GetString("perditsoShporten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Coupon Code.
        /// </summary>
        internal static string perdorKodin {
            get {
                return ResourceManager.GetString("perdorKodin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string sasia {
            get {
                return ResourceManager.GetString("sasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty..
        /// </summary>
        internal static string shportaZbrazet {
            get {
                return ResourceManager.GetString("shportaZbrazet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string shteti {
            get {
                return ResourceManager.GetString("shteti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string subtotali {
            get {
                return ResourceManager.GetString("subtotali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Total.
        /// </summary>
        internal static string totali {
            get {
                return ResourceManager.GetString("totali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total products.
        /// </summary>
        internal static string totalProdukte {
            get {
                return ResourceManager.GetString("totalProdukte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total shipping.
        /// </summary>
        internal static string totalTransporti {
            get {
                return ResourceManager.GetString("totalTransporti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to Checkout.
        /// </summary>
        internal static string vazhdo {
            get {
                return ResourceManager.GetString("vazhdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to checkout.
        /// </summary>
        internal static string vazhdoniBlerje {
            get {
                return ResourceManager.GetString("vazhdoniBlerje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate Shipping And Tax.
        /// </summary>
        internal static string vleresimiTransportit {
            get {
                return ResourceManager.GetString("vleresimiTransportit", resourceCulture);
            }
        }
    }
}
