//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Wishlist {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Wishlist.Index.sq", typeof(Index_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmimi.
        /// </summary>
        internal static string cmimi {
            get {
                return ResourceManager.GetString("cmimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri i produktit.
        /// </summary>
        internal static string emriProduktit {
            get {
                return ResourceManager.GetString("emriProduktit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        internal static string foto {
            get {
                return ResourceManager.GetString("foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e dëshirave.
        /// </summary>
        internal static string listaDeshirave {
            get {
                return ResourceManager.GetString("listaDeshirave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e dëshirave është e zbrazët..
        /// </summary>
        internal static string listaDeshiraveZbrazet {
            get {
                return ResourceManager.GetString("listaDeshiraveZbrazet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Në stok.
        /// </summary>
        internal static string neStok {
            get {
                return ResourceManager.GetString("neStok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk ka në stok.
        /// </summary>
        internal static string nukKaStok {
            get {
                return ResourceManager.GetString("nukKaStok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto në shportë.
        /// </summary>
        internal static string shtoNeShporte {
            get {
                return ResourceManager.GetString("shtoNeShporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoku.
        /// </summary>
        internal static string stoku {
            get {
                return ResourceManager.GetString("stoku", resourceCulture);
            }
        }
    }
}
