//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Layout_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Shared._Layout.en", typeof(_Layout_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string arka {
            get {
                return ResourceManager.GetString("arka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string ckycu {
            get {
                return ResourceManager.GetString("ckycu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string gjuha {
            get {
                return ResourceManager.GetString("gjuha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info:.
        /// </summary>
        internal static string infoKontakt {
            get {
                return ResourceManager.GetString("infoKontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search here.
        /// </summary>
        internal static string kerkoHome {
            get {
                return ResourceManager.GetString("kerkoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for products....
        /// </summary>
        internal static string kerkoniProdukte {
            get {
                return ResourceManager.GetString("kerkoniProdukte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string kontakti {
            get {
                return ResourceManager.GetString("kontakti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        internal static string kthimet {
            get {
                return ResourceManager.GetString("kthimet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string kycu {
            get {
                return ResourceManager.GetString("kycu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store links.
        /// </summary>
        internal static string linqet {
            get {
                return ResourceManager.GetString("linqet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        internal static string listaDeshirave {
            get {
                return ResourceManager.GetString("listaDeshirave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string llogariaIme {
            get {
                return ResourceManager.GetString("llogariaIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string mbeshtetja {
            get {
                return ResourceManager.GetString("mbeshtetja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Support.
        /// </summary>
        internal static string mbeshtetjaKonsumatorit {
            get {
                return ResourceManager.GetString("mbeshtetjaKonsumatorit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string monedha {
            get {
                return ResourceManager.GetString("monedha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us.
        /// </summary>
        internal static string naNdiqni {
            get {
                return ResourceManager.GetString("naNdiqni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string pagesa {
            get {
                return ResourceManager.GetString("pagesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Policy.
        /// </summary>
        internal static string politikatTransportit {
            get {
                return ResourceManager.GetString("politikatTransportit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string privatesia {
            get {
                return ResourceManager.GetString("privatesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string produkte {
            get {
                return ResourceManager.GetString("produkte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string regjistrohu {
            get {
                return ResourceManager.GetString("regjistrohu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All right reserved..
        /// </summary>
        internal static string rights {
            get {
                return ResourceManager.GetString("rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string rrethNesh {
            get {
                return ResourceManager.GetString("rrethNesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string shporta {
            get {
                return ResourceManager.GetString("shporta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Cart.
        /// </summary>
        internal static string shportaJuaj {
            get {
                return ResourceManager.GetString("shportaJuaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty..
        /// </summary>
        internal static string shportaZbrazet {
            get {
                return ResourceManager.GetString("shportaZbrazet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        internal static string statusiPorosise {
            get {
                return ResourceManager.GetString("statusiPorosise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string subtotali {
            get {
                return ResourceManager.GetString("subtotali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string telefoni {
            get {
                return ResourceManager.GetString("telefoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        internal static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment.
        /// </summary>
        internal static string transporti {
            get {
                return ResourceManager.GetString("transporti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to checkout.
        /// </summary>
        internal static string vazhdoPagese {
            get {
                return ResourceManager.GetString("vazhdoPagese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to our store.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Technocy?.
        /// </summary>
        internal static string whyUs {
            get {
                return ResourceManager.GetString("whyUs", resourceCulture);
            }
        }
    }
}
