//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Layout_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Shared._Layout.sq", typeof(_Layout_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka.
        /// </summary>
        internal static string arka {
            get {
                return ResourceManager.GetString("arka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çkyçu.
        /// </summary>
        internal static string ckycu {
            get {
                return ResourceManager.GetString("ckycu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Maili.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjuha.
        /// </summary>
        internal static string gjuha {
            get {
                return ResourceManager.GetString("gjuha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informata për kontakt:.
        /// </summary>
        internal static string infoKontakt {
            get {
                return ResourceManager.GetString("infoKontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërkoni këtu.
        /// </summary>
        internal static string kerkoHome {
            get {
                return ResourceManager.GetString("kerkoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërkoni produkte....
        /// </summary>
        internal static string kerkoniProdukte {
            get {
                return ResourceManager.GetString("kerkoniProdukte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakti.
        /// </summary>
        internal static string kontakti {
            get {
                return ResourceManager.GetString("kontakti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kthimet.
        /// </summary>
        internal static string kthimet {
            get {
                return ResourceManager.GetString("kthimet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçu.
        /// </summary>
        internal static string kycu {
            get {
                return ResourceManager.GetString("kycu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linqet e dyqanit.
        /// </summary>
        internal static string linqet {
            get {
                return ResourceManager.GetString("linqet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e dëshirave.
        /// </summary>
        internal static string listaDeshirave {
            get {
                return ResourceManager.GetString("listaDeshirave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llogaria ime.
        /// </summary>
        internal static string llogariaIme {
            get {
                return ResourceManager.GetString("llogariaIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbështetja.
        /// </summary>
        internal static string mbeshtetja {
            get {
                return ResourceManager.GetString("mbeshtetja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbështetja ndaj konsumatorit.
        /// </summary>
        internal static string mbeshtetjaKonsumatorit {
            get {
                return ResourceManager.GetString("mbeshtetjaKonsumatorit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monedha.
        /// </summary>
        internal static string monedha {
            get {
                return ResourceManager.GetString("monedha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na ndiqni.
        /// </summary>
        internal static string naNdiqni {
            get {
                return ResourceManager.GetString("naNdiqni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagesa.
        /// </summary>
        internal static string pagesa {
            get {
                return ResourceManager.GetString("pagesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politikat e transportit.
        /// </summary>
        internal static string politikatTransportit {
            get {
                return ResourceManager.GetString("politikatTransportit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privatësia.
        /// </summary>
        internal static string privatesia {
            get {
                return ResourceManager.GetString("privatesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkte.
        /// </summary>
        internal static string produkte {
            get {
                return ResourceManager.GetString("produkte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regjistrohu.
        /// </summary>
        internal static string regjistrohu {
            get {
                return ResourceManager.GetString("regjistrohu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të gjitha të drejtat e rezervuara.
        /// </summary>
        internal static string rights {
            get {
                return ResourceManager.GetString("rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rreth Nesh.
        /// </summary>
        internal static string rrethNesh {
            get {
                return ResourceManager.GetString("rrethNesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shporta.
        /// </summary>
        internal static string shporta {
            get {
                return ResourceManager.GetString("shporta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shporta juaj.
        /// </summary>
        internal static string shportaJuaj {
            get {
                return ResourceManager.GetString("shportaJuaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shporta juaj është e zbrazët..
        /// </summary>
        internal static string shportaZbrazet {
            get {
                return ResourceManager.GetString("shportaZbrazet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusi porosisë.
        /// </summary>
        internal static string statusiPorosise {
            get {
                return ResourceManager.GetString("statusiPorosise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotali.
        /// </summary>
        internal static string subtotali {
            get {
                return ResourceManager.GetString("subtotali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoni:.
        /// </summary>
        internal static string telefoni {
            get {
                return ResourceManager.GetString("telefoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termat dhe kushtet.
        /// </summary>
        internal static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporti.
        /// </summary>
        internal static string transporti {
            get {
                return ResourceManager.GetString("transporti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vazhdo me pagesë.
        /// </summary>
        internal static string vazhdoPagese {
            get {
                return ResourceManager.GetString("vazhdoPagese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirësevini në dyqanin tonë.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pse Technocy?.
        /// </summary>
        internal static string whyUs {
            get {
                return ResourceManager.GetString("whyUs", resourceCulture);
            }
        }
    }
}
