//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Payment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Payment.Index.en", typeof(Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholdre.
        /// </summary>
        internal static string cardholder {
            get {
                return ResourceManager.GetString("cardholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cvv.
        /// </summary>
        internal static string cvv {
            get {
                return ResourceManager.GetString("cvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT DETAILS.
        /// </summary>
        internal static string detajetPageses {
            get {
                return ResourceManager.GetString("detajetPageses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string emriPlote {
            get {
                return ResourceManager.GetString("emriPlote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string numriKartes {
            get {
                return ResourceManager.GetString("numriKartes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        internal static string skadimi {
            get {
                return ResourceManager.GetString("skadimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Payment.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE.
        /// </summary>
        internal static string vazhdo {
            get {
                return ResourceManager.GetString("vazhdo", resourceCulture);
            }
        }
    }
}
