//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Views.Profile.Index.sq", typeof(Index_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        internal static string adresa {
            get {
                return ResourceManager.GetString("adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluar.
        /// </summary>
        internal static string anuluar {
            get {
                return ResourceManager.GetString("anuluar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballina.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detajet e llogarisë.
        /// </summary>
        internal static string detajetLlogarise {
            get {
                return ResourceManager.GetString("detajetLlogarise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emaili.
        /// </summary>
        internal static string emaili {
            get {
                return ResourceManager.GetString("emaili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        internal static string emri {
            get {
                return ResourceManager.GetString("emri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Nisur.
        /// </summary>
        internal static string eNisur {
            get {
                return ResourceManager.GetString("eNisur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi aktual.
        /// </summary>
        internal static string fjalekalimiAktual {
            get {
                return ResourceManager.GetString("fjalekalimiAktual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i ri.
        /// </summary>
        internal static string fjalekalimiRi {
            get {
                return ResourceManager.GetString("fjalekalimiRi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përshëndetje,.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi Postal.
        /// </summary>
        internal static string kodiPostal {
            get {
                return ResourceManager.GetString("kodiPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompletuar.
        /// </summary>
        internal static string kompletuar {
            get {
                return ResourceManager.GetString("kompletuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmo fjalëkalimin e ri.
        /// </summary>
        internal static string konfirmoFjalekaliminRi {
            get {
                return ResourceManager.GetString("konfirmoFjalekaliminRi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmuar.
        /// </summary>
        internal static string konfirmuar {
            get {
                return ResourceManager.GetString("konfirmuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbiemri.
        /// </summary>
        internal static string mbiemri {
            get {
                return ResourceManager.GetString("mbiemri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mënyrat e pagesës.
        /// </summary>
        internal static string menyratPageses {
            get {
                return ResourceManager.GetString("menyratPageses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk mund ta ruani ende mënyrën tuaj të pagesës..
        /// </summary>
        internal static string menyratPagesesMsg {
            get {
                return ResourceManager.GetString("menyratPagesesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho adresën.
        /// </summary>
        internal static string ndryshoAdresen {
            get {
                return ResourceManager.GetString("ndryshoAdresen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho fjalëkalimin.
        /// </summary>
        internal static string ndryshoFjalekalimin {
            get {
                return ResourceManager.GetString("ndryshoFjalekalimin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nëse nuk jeni.
        /// </summary>
        internal static string nukJeni {
            get {
                return ResourceManager.GetString("nukJeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju nuk keni ende porosi të kryera..
        /// </summary>
        internal static string nukKeniPorosiTeKryera {
            get {
                return ResourceManager.GetString("nukKeniPorosiTeKryera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porosia.
        /// </summary>
        internal static string porosia {
            get {
                return ResourceManager.GetString("porosia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porositë.
        /// </summary>
        internal static string porosite {
            get {
                return ResourceManager.GetString("porosite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nga profili i llogarisë suaj mund të kontrolloni dhe shikoni lehtësisht porositë tuaja më të fundit, të menaxhoni adresat tuaja të transportit dhe faturimit dhe të modifikoni fjalëkalimin dhe detajet e llogarisë tuaj..
        /// </summary>
        internal static string profileDetails {
            get {
                return ResourceManager.GetString("profileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili.
        /// </summary>
        internal static string profili {
            get {
                return ResourceManager.GetString("profili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruaj Ndryshimet.
        /// </summary>
        internal static string ruajNdryshimet {
            get {
                return ResourceManager.GetString("ruajNdryshimet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiko.
        /// </summary>
        internal static string shiko {
            get {
                return ResourceManager.GetString("shiko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusi.
        /// </summary>
        internal static string statusi {
            get {
                return ResourceManager.GetString("statusi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoni.
        /// </summary>
        internal static string telefoni {
            get {
                return ResourceManager.GetString("telefoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totali.
        /// </summary>
        internal static string totali {
            get {
                return ResourceManager.GetString("totali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifikimi manual i nevojshëm.
        /// </summary>
        internal static string verifikimManual {
            get {
                return ResourceManager.GetString("verifikimManual", resourceCulture);
            }
        }
    }
}
